// قائمة السور القرآنية الكريمة مع عدد صفحات كل سورة في المصحف القياسي (604 صفحات)
export const surahs = [
  { id: 1, name: "الفاتحة", verses: 7, pages: 1 },
  { id: 2, name: "البقرة", verses: 286, pages: 48 },
  { id: 3, name: "آل عمران", verses: 200, pages: 27 },
  { id: 4, name: "النساء", verses: 176, pages: 30 },
  { id: 5, name: "المائدة", verses: 120, pages: 21 },
  { id: 6, name: "الأنعام", verses: 165, pages: 23 },
  { id: 7, name: "الأعراف", verses: 206, pages: 26 },
  { id: 8, name: "الأنفال", verses: 75, pages: 10 },
  { id: 9, name: "التوبة", verses: 129, pages: 21 },
  { id: 10, name: "يونس", verses: 109, pages: 14 },
  { id: 11, name: "هود", verses: 123, pages: 14 },
  { id: 12, name: "يوسف", verses: 111, pages: 13 },
  { id: 13, name: "الرعد", verses: 43, pages: 6 },
  { id: 14, name: "ابراهيم", verses: 52, pages: 7 },
  { id: 15, name: "الحجر", verses: 99, pages: 6 },
  { id: 16, name: "النحل", verses: 128, pages: 14 },
  { id: 17, name: "الإسراء", verses: 111, pages: 12 },
  { id: 18, name: "الكهف", verses: 110, pages: 12 },
  { id: 19, name: "مريم", verses: 98, pages: 7 },
  { id: 20, name: "طه", verses: 135, pages: 10 },
  { id: 21, name: "الأنبياء", verses: 112, pages: 10 },
  { id: 22, name: "الحج", verses: 78, pages: 10 },
  { id: 23, name: "المؤمنون", verses: 118, pages: 8 },
  { id: 24, name: "النور", verses: 64, pages: 10 },
  { id: 25, name: "الفرقان", verses: 77, pages: 9 },
  { id: 26, name: "الشعراء", verses: 227, pages: 11 },
  { id: 27, name: "النمل", verses: 93, pages: 9 },
  { id: 28, name: "القصص", verses: 88, pages: 11 },
  { id: 29, name: "العنكبوت", verses: 69, pages: 7 },
  { id: 30, name: "الروم", verses: 60, pages: 7 },
  { id: 31, name: "لقمان", verses: 34, pages: 4 },
  { id: 32, name: "السجدة", verses: 30, pages: 3 },
  { id: 33, name: "الأحزاب", verses: 73, pages: 9 },
  { id: 34, name: "سبأ", verses: 54, pages: 6 },
  { id: 35, name: "فاطر", verses: 45, pages: 6 },
  { id: 36, name: "يس", verses: 83, pages: 6 },
  { id: 37, name: "الصافات", verses: 182, pages: 9 },
  { id: 38, name: "ص", verses: 88, pages: 5 },
  { id: 39, name: "الزمر", verses: 75, pages: 9 },
  { id: 40, name: "غافر", verses: 85, pages: 9 },
  { id: 41, name: "فصلت", verses: 54, pages: 6 },
  { id: 42, name: "الشورى", verses: 53, pages: 6 },
  { id: 43, name: "الزخرف", verses: 89, pages: 7 },
  { id: 44, name: "الدخان", verses: 59, pages: 3 },
  { id: 45, name: "الجاثية", verses: 37, pages: 4 },
  { id: 46, name: "الأحقاف", verses: 35, pages: 5 },
  { id: 47, name: "محمد", verses: 38, pages: 4 },
  { id: 48, name: "الفتح", verses: 29, pages: 5 },
  { id: 49, name: "الحجرات", verses: 18, pages: 2.5 },
  { id: 50, name: "ق", verses: 45, pages: 3 },
  { id: 51, name: "الذاريات", verses: 60, pages: 3 },
  { id: 52, name: "الطور", verses: 49, pages: 2.5 },
  { id: 53, name: "النجم", verses: 62, pages: 2.5 },
  { id: 54, name: "القمر", verses: 55, pages: 3 },
  { id: 55, name: "الرحمن", verses: 78, pages: 3 },
  { id: 56, name: "الواقعة", verses: 96, pages: 3 },
  { id: 57, name: "الحديد", verses: 29, pages: 4 },
  { id: 58, name: "المجادلة", verses: 22, pages: 3 },
  { id: 59, name: "الحشر", verses: 24, pages: 3 },
  { id: 60, name: "الممتحنة", verses: 13, pages: 2.5 },
  { id: 61, name: "الصف", verses: 14, pages: 1.5 },
  { id: 62, name: "الجمعة", verses: 11, pages: 1.2 },
  { id: 63, name: "المنافقون", verses: 11, pages: 1.2 },
  { id: 64, name: "التغابن", verses: 18, pages: 2 },
  { id: 65, name: "الطلاق", verses: 12, pages: 2 },
  { id: 66, name: "التحريم", verses: 12, pages: 2 },
  { id: 67, name: "الملك", verses: 30, pages: 2.5 },
  { id: 68, name: "القلم", verses: 52, pages: 2 },
  { id: 69, name: "الحاقة", verses: 52, pages: 2 },
  { id: 70, name: "المعارج", verses: 44, pages: 2 },
  { id: 71, name: "نوح", verses: 28, pages: 1.5 },
  { id: 72, name: "الجن", verses: 28, pages: 2 },
  { id: 73, name: "المزمل", verses: 20, pages: 1.5 },
  { id: 74, name: "المدثر", verses: 56, pages: 2 },
  { id: 75, name: "القيامة", verses: 40, pages: 1.2 },
  { id: 76, name: "الانسان", verses: 31, pages: 2 },
  { id: 77, name: "المرسلات", verses: 50, pages: 1.8 },
  { id: 78, name: "النبأ", verses: 40, pages: 1.5 },
  { id: 79, name: "النازعات", verses: 46, pages: 1.5 },
  { id: 80, name: "عبس", verses: 42, pages: 1.2 },
  { id: 81, name: "التكوير", verses: 29, pages: 1 },
  { id: 82, name: "الانفطار", verses: 19, pages: 0.8 },
  { id: 83, name: "المطففين", verses: 36, pages: 1.8 },
  { id: 84, name: "الانشقاق", verses: 25, pages: 1 },
  { id: 85, name: "البروج", verses: 22, pages: 1 },
  { id: 86, name: "الطارق", verses: 17, pages: 0.8 },
  { id: 87, name: "الأعلى", verses: 19, pages: 0.8 },
  { id: 88, name: "الغاشية", verses: 26, pages: 1 },
  { id: 89, name: "الفجر", verses: 30, pages: 1.2 },
  { id: 90, name: "البلد", verses: 20, pages: 1 },
  { id: 91, name: "الشمس", verses: 15, pages: 0.8 },
  { id: 92, name: "الليل", verses: 21, pages: 0.8 },
  { id: 93, name: "الضحى", verses: 11, pages: 0.5 },
  { id: 94, name: "الشرح", verses: 8, pages: 0.3 },
  { id: 95, name: "التين", verses: 8, pages: 0.5 },
  { id: 96, name: "العلق", verses: 19, pages: 0.8 },
  { id: 97, name: "القدر", verses: 5, pages: 0.3 },
  { id: 98, name: "البينة", verses: 8, pages: 1 },
  { id: 99, name: "الزلزلة", verses: 8, pages: 0.5 },
  { id: 100, name: "العاديات", verses: 11, pages: 0.5 },
  { id: 101, name: "القارعة", verses: 11, pages: 0.5 },
  { id: 102, name: "التكاثر", verses: 8, pages: 0.5 },
  { id: 103, name: "العصر", verses: 3, pages: 0.3 },
  { id: 104, name: "الهمزة", verses: 9, pages: 0.3 },
  { id: 105, name: "الفيل", verses: 5, pages: 0.3 },
  { id: 106, name: "قريش", verses: 4, pages: 0.3 },
  { id: 107, name: "الماعون", verses: 7, pages: 0.3 },
  { id: 108, name: "الكوثر", verses: 3, pages: 0.2 },
  { id: 109, name: "الكافرون", verses: 6, pages: 0.3 },
  { id: 110, name: "النصر", verses: 3, pages: 0.2 },
  { id: 111, name: "المسد", verses: 5, pages: 0.2 },
  { id: 112, name: "الإخلاص", verses: 4, pages: 0.2 },
  { id: 113, name: "الفلق", verses: 5, pages: 0.2 },
  { id: 114, name: "الناس", verses: 6, pages: 0.2 },
] as const;

export type Surah = typeof surahs[number];

/**
 * دالة لحساب عدد الصفحات القياسية المكافئة لقدر معين من السورة
 */
export function calculateStandardPages(surahId: number, fromVerse: number, toVerse: number): number {
  if (toVerse < fromVerse || fromVerse <= 0) return 0;
  const surah = surahs.find(s => s.id === surahId);
  if (!surah || !surah.pages || surah.verses <= 0) return 0;
  const count = Math.max(0, toVerse - fromVerse + 1);
  const actualCount = Math.min(count, surah.verses);
  return Number(((actualCount * surah.pages) / surah.verses).toFixed(3));
}
